In [1]:
import os, subprocess
import json
import uproot
import awkward as ak
import numpy as np
from coffea import processor, util, hist
import pandas as pd
import pickle

/opt/conda/lib/python3.8/site-packages/coffea/util.py:154: FutureWarning: In coffea version v2023.3.0 (target date: 31 Mar 2023), this will be an error.
(Set coffea.deprecations_as_errors = True to get a stack trace now.)
ImportError: coffea.hist is deprecated
  warnings.warn(message, FutureWarning)

In [2]:
with open('../lumi.json') as f:
    lumis = json.load(f)

with open('../xsec.json') as f:
  xs = json.load(f)

with open('../pmap.json') as f:
  pmap = json.load(f)

In [3]:
year = '2017'
infiles = subprocess.getoutput("ls ../infiles-nano/"+year+"*.json").split()
coffeadir_prefix = '../outfiles-plots/'
outsum = processor.dict_accumulator()

In [4]:
repickle = True
# Check if pickle exists, don't recreate it if it does
picklename = '../'+year+'/cutflow.pkl'
#if os.path.isfile(picklename):
#    repickle = False

In [5]:
if repickle:

    for this_file in infiles:
    
        print(this_file)
        index = this_file.split("_")[1].split(".json")[0]
        filename = coffeadir_prefix+year+"_dask_"+index+".coffea"
        
        with open(this_file, 'r') as openfile:
            samples = json.load(openfile)

        print(filename)
        if os.path.isfile(filename):
            out = util.load(filename)

            if len(outsum.keys()) == 0:
                outsum['cutflow'] = out['cutflow']
                outsum['sumw'] = out['sumw']
            else:
                outsum['cutflow'].add(out['cutflow'])
                outsum['sumw'].add(out['sumw'])
                
            del out
        else:
            print('Missing file '+index,index)
            #print("File " + filename + " is missing")  
            
    scale_lumi = {k: xs[k] * 1000 *lumis[year] / w for k, w in outsum['sumw'].items()}
    outsum['cutflow'].scale(scale_lumi, 'dataset')
    cutflow = outsum['cutflow'].group('dataset', hist.Cat('process', 'Process'), pmap)
    
    del outsum
    
    outfile = open(picklename, 'wb')
    pickle.dump(cutflow, outfile, protocol=-1)
    outfile.close()

../infiles-nano/2017_EWKV.json
../outfiles-plots/2017_dask_EWKV.coffea
../infiles-nano/2017_QCD.json
../outfiles-plots/2017_dask_QCD.coffea
../infiles-nano/2017_VBF.json
../outfiles-plots/2017_dask_VBF.coffea
../infiles-nano/2017_VV.json
../outfiles-plots/2017_dask_VV.coffea
../infiles-nano/2017_WH.json
../outfiles-plots/2017_dask_WH.coffea
../infiles-nano/2017_Wjets.json
../outfiles-plots/2017_dask_Wjets.coffea
../infiles-nano/2017_ZH.json
../outfiles-plots/2017_dask_ZH.coffea
../infiles-nano/2017_Zjets.json
../outfiles-plots/2017_dask_Zjets.coffea
../infiles-nano/2017_data.json
../outfiles-plots/2017_dask_data.coffea
../infiles-nano/2017_ggF.json
../outfiles-plots/2017_dask_ggF.coffea
../infiles-nano/2017_muondata.json
../outfiles-plots/2017_dask_muondata.coffea
../infiles-nano/2017_singlet.json
../outfiles-plots/2017_dask_singlet.coffea
../infiles-nano/2017_ttH.json
../outfiles-plots/2017_dask_ttH.coffea
../infiles-nano/2017_ttbar.json
../outfiles-plots/2017_dask_ttbar.coffea
../infiles-nano/2017_ttbarBoosted.json
../outfiles-plots/2017_dask_ttbarBoosted.coffea

/opt/conda/lib/python3.8/site-packages/coffea/hist/hist_tools.py:376: RuntimeWarning: Not all requested indices present in <Cat (name=dataset) instance at 0x7f0b273d7a00>
  warnings.warn(

In [6]:
# Read the histogram from the pickle file
templates = pickle.load(open(picklename,'rb'))

In [7]:
cutflow = templates.sum('genflavor').integrate('region',['signal-ggf'])
cutflow

In [8]:
cutflow.values()

{('QCD',): array([1.15016018e+08, 1.15016018e+08, 1.15016018e+08, 1.14596209e+08,
        1.50784534e+07, 1.50784534e+07, 4.07053695e+06, 3.85832508e+06,
        3.81115520e+06, 3.64778488e+06, 3.50939036e+06, 1.08609214e+04,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('ttbar',): array([1.50748099e+07, 1.50748099e+07, 1.50748099e+07, 1.50633979e+07,
        1.48789120e+05, 1.48789120e+05, 5.44916291e+04, 2.84997791e+04,
        2.21236054e+04, 1.33626792e+04, 1.29742964e+04, 1.49928154e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('ttbarBoosted',): array([1.82682479e+06, 1.82682479e+06, 1.82682479e+06, 1.82451769e+06,
        1.10298326e+05, 1.10298326e+05, 4.32992456e+04, 2.05698002e+04,
        1.56571720e+04, 9.89180697e+03, 9.61162900e+03, 1.20063475e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('singlet',): array([4.02640178e+06, 4.02640178e+06, 4.02640178e+06, 4.02398875e+06,
        1.70255494e+04, 1.70255494e+04, 7.12295530e+03, 4.04338978e+03,
        3.23215499e+03, 2.28521954e+03, 2.19440129e+03, 2.46406803e+01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('Wjets',): array([1.99717252e+07, 1.99717252e+07, 1.99717252e+07, 1.99463889e+07,
        3.65942247e+05, 3.65942247e+05, 1.45299726e+05, 1.37406987e+05,
        1.25201802e+05, 1.04401374e+05, 1.01866472e+05, 3.24780892e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('Zjets',): array([3.38805871e+06, 3.38805871e+06, 3.38805871e+06, 3.38159745e+06,
        1.31948692e+05, 1.31948692e+05, 5.77651080e+04, 5.33082066e+04,
        5.21353319e+04, 3.99952827e+04, 3.90345846e+04, 1.67359610e+03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('VV',): array([2.00213384e+06, 2.00213384e+06, 2.00213384e+06, 2.00096461e+06,
        4.85925868e+03, 4.85925868e+03, 2.68856572e+03, 2.50787283e+03,
        1.92711799e+03, 1.42525050e+03, 1.38538304e+03, 3.19755796e+01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('EWKZ',): array([3.38522617e+05, 3.38522617e+05, 3.38522617e+05, 3.38132501e+05,
        3.82644236e+03, 3.82644236e+03, 2.00790648e+03, 1.84844493e+03,
        1.56775796e+03, 1.07372532e+03, 9.32842406e+02, 4.25938687e+01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('EWKW',): array([2.30270137e+06, 2.30270137e+06, 2.30270137e+06, 2.30055882e+06,
        2.37740001e+04, 2.37740001e+04, 1.25165393e+04, 9.09091422e+03,
        6.01308800e+03, 4.97480361e+03, 4.28656235e+03, 3.54046229e+01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('ggF',): array([2204.76384867, 2204.76384867, 2204.76384867, 2200.66134553,
         286.71717849,  286.71717849,  143.70248293,  126.22007354,
         121.52171707,  115.70819766,  110.32014259,   32.15679856,
           0.        ,    0.        ,    0.        ]),
 ('VBF',): array([1.33362495e+04, 1.33362495e+04, 1.33362495e+04, 1.33246719e+04,
        1.18504465e+02, 1.18504465e+02, 6.70458522e+01, 6.00140121e+01,
        5.71188982e+01, 5.38758614e+01, 3.25219650e+01, 1.04710374e+01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('WH',): array([1.13895813e+04, 1.13895813e+04, 1.13895813e+04, 1.13825777e+04,
        1.10275321e+02, 1.10275321e+02, 5.72101939e+01, 4.58830070e+01,
        3.27996324e+01, 2.77901448e+01, 2.73397138e+01, 7.17290509e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('ZH',): array([4.64646594e+03, 4.64646594e+03, 4.64646594e+03, 4.64243877e+03,
        7.96586868e+01, 7.96586868e+01, 4.18135907e+01, 2.84174618e+01,
        2.18008956e+01, 1.78162250e+01, 1.74965585e+01, 4.21876733e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('ttH',): array([6.63065515e+03, 6.63065515e+03, 6.63065515e+03, 6.62262416e+03,
        3.06149307e+02, 3.06149307e+02, 1.10848402e+02, 3.59573667e+01,
        2.78137926e+01, 1.64638895e+01, 1.61437530e+01, 1.69233988e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 ('data',): array([2.1756344e+08, 7.7388072e+07, 7.4848171e+07, 7.4607789e+07,
        1.7776278e+07, 1.7776278e+07, 4.2505630e+06, 3.9736810e+06,
        3.8648730e+06, 3.6642630e+06, 3.5416960e+06, 9.8120000e+03,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00]),
 ('muondata',): array([3.2593848e+07, 2.0493490e+06, 1.9901450e+06, 1.9794580e+06,
        4.2803600e+05, 4.2803600e+05, 1.2452800e+05, 1.0249800e+05,
        9.0370000e+04, 7.3757000e+04, 7.0048000e+04, 8.9500000e+02,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00])}

In [9]:
df1 = pd.DataFrame([])

df1['ggF'] = cutflow.values()[('ggF',)]
df1['VBF'] = cutflow.values()[('VBF',)]
df1['WH'] = cutflow.values()[('WH',)]
df1['ZH'] = cutflow.values()[('ZH',)]
df1['ttH'] = cutflow.values()[('ttH',)]


df1
df1 = df1[:-3].astype('int')
df1
df1.index = ['nothing','trigger','lumimask','metfilter','minjetkin','jetid','n2ddt','antiak4btagMediumOppHem','met','noleptons','notvbf','ddbpass']
df1

                          ggF    VBF     WH    ZH   ttH
nothing                  2204  13336  11389  4646  6630
trigger                  2204  13336  11389  4646  6630
lumimask                 2204  13336  11389  4646  6630
metfilter                2200  13324  11382  4642  6622
minjetkin                 286    118    110    79   306
jetid                     286    118    110    79   306
n2ddt                     143     67     57    41   110
antiak4btagMediumOppHem   126     60     45    28    35
met                       121     57     32    21    27
noleptons                 115     53     27    17    16
notvbf                    110     32     27    17    16
ddbpass                    32     10      7     4     1

In [10]:
df1 = df1[4:-2]
df1.index = ['Jet kinematics','Jet ID','Jet $N_2^\text{DDT}$','Opp. hem. b veto','MET $<$ 140 GeV','No leptons']
df1.to_latex(buf=year+'/cutflow-sig.tex')
df1

                      ggF  VBF   WH  ZH  ttH
Jet kinematics        286  118  110  79  306
Jet ID                286  118  110  79  306
Jet $N_2^\text{DDT}$  143   67   57  41  110
Opp. hem. b veto      126   60   45  28   35
MET $<$ 140 GeV       121   57   32  21   27
No leptons            115   53   27  17   16

In [11]:
df2 = pd.DataFrame([])

df2['QCD'] = cutflow.values()[('QCD',)]
df2['Wjets'] = cutflow.values()[('Wjets',)]
df2['Zjets'] = cutflow.values()[('Zjets',)]
df2['EWKW'] = cutflow.values()[('EWKW',)]
df2['EWKZ'] = cutflow.values()[('EWKZ',)]
df2['VV'] = cutflow.values()[('VV',)]
df2['ttbar'] = cutflow.values()[('ttbar',)]
df2['singlet'] = cutflow.values()[('singlet',)]

df2 = df2[:-3].astype('int')
df2.index = ['nothing','trigger','lumimask','metfilter','minjetkin','jetid','n2ddt','antiak4btagMediumOppHem','met','noleptons','notvbf','ddbpass']
df2

,QCD,Wjets,Zjets,EWKW,EWKZ,VV,ttbar,singlet
nothing,115016018,19971725,3388058,2302701,338522,2002133,15074809,4026401
trigger,115016018,19971725,3388058,2302701,338522,2002133,15074809,4026401
lumimask,115016018,19971725,3388058,2302701,338522,2002133,15074809,4026401
metfilter,114596209,19946388,3381597,2300558,338132,2000964,15063397,4023988
minjetkin,15078453,365942,131948,23774,3826,4859,148789,17025
jetid,15078453,365942,131948,23774,3826,4859,148789,17025
n2ddt,4070536,145299,57765,12516,2007,2688,54491,7122
antiak4btagMediumOppHem,3858325,137406,53308,9090,1848,2507,28499,4043
met,3811155,125201,52135,6013,1567,1927,22123,3232
noleptons,3647784,104401,39995,4974,1073,1425,13362,2285
notvbf,3509390,101866,39034,4286,932,1385,12974,2194
ddbpass,10860,324,1673,35,42,31,149,24

In [12]:
df2 = df2[4:-2]
df2.index = ['Jet kinematics','Jet ID','Jet $N_2^\text{DDT}$','Opp. hem. b veto','MET $<$ 140 GeV','No leptons']
df2.to_latex(buf=year+'/cutflow-bkg.tex')
df2

,QCD,Wjets,Zjets,EWKW,EWKZ,VV,ttbar,singlet
Jet kinematics,15078453,365942,131948,23774,3826,4859,148789,17025
Jet ID,15078453,365942,131948,23774,3826,4859,148789,17025
Jet $N_2^\text{DDT}$,4070536,145299,57765,12516,2007,2688,54491,7122
Opp. hem. b veto,3858325,137406,53308,9090,1848,2507,28499,4043
MET $<$ 140 GeV,3811155,125201,52135,6013,1567,1927,22123,3232
No leptons,3647784,104401,39995,4974,1073,1425,13362,2285